name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          docker build -t housepriceapi .
          docker tag housepriceapi housepriceapi.azurewebsites.net/housepriceapi
          docker save housepriceapi | gzip > housepriceapi.tar.gz

      - name: Deploy container to Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: housepriceapi
          slot-name: production
          package: housepriceapi.tar.gz
