name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and tag Docker image
      run: |
        docker build -t housepriceapi .

    - name: Save Docker image as tarball
      run: |
        mkdir -p deploy-dir
        docker save housepriceapi | gzip > deploy-dir/housepriceapi.tar.gz

    - name: Deploy to Web App using tarball
      uses: azure/webapps-deploy@v2
      with:
        app-name: housepriceapi
        package: deploy-dir/housepriceapi.tar.gz
